"""Tab title unique

Revision ID: 4fc6259d3b6a
Revises: eb8d452a379f
Create Date: 2018-05-16 01:02:33.418003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc6259d3b6a'
down_revision = 'eb8d452a379f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tab_title'), 'tab', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_title'), table_name='tab')
    # ### end Alembic commands ###
